"""add max_retries setting

Revision ID: 13bde15ea57c
Revises: 51bf10f9c974
Create Date: 2026-03-29 13:11:40.758580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13bde15ea57c'
down_revision: Union[str, Sequence[str], None] = '51bf10f9c974'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [c['name'] for c in inspector.get_columns('app_settings')]
    
    if 'max_retries' not in columns:
        op.add_column('app_settings', sa.Column('max_retries', sa.Integer(), nullable=True))
        
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_settings', 'max_retries')
    # ### end Alembic commands ###
