"""add max_tags

Revision ID: 1a2b3c4d5e6f
Revises: 81706ec7e3d3
Create Date: 2026-04-05 10:50:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a2b3c4d5e6f'
down_revision: Union[str, None] = '65fb48795450'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_settings', sa.Column('max_tags', sa.Integer(), nullable=True))
    op.execute("UPDATE app_settings SET max_tags = 5")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_settings', 'max_tags')
    # ### end Alembic commands ###
