"""granular ai metadata settings

Revision ID: 3c4d5e6f7a8b
Revises: 2b3c4d5e6f7a
Create Date: 2026-04-05 14:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c4d5e6f7a8b'
down_revision: Union[str, None] = '2b3c4d5e6f7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_settings', sa.Column('generate_correspondent', sa.Boolean(), nullable=True))
    op.add_column('app_settings', sa.Column('generate_document_type', sa.Boolean(), nullable=True))
    op.add_column('app_settings', sa.Column('generate_tags', sa.Boolean(), nullable=True))
    op.execute("UPDATE app_settings SET generate_correspondent = COALESCE(enable_ai_metadata_creation, 0)")
    op.execute("UPDATE app_settings SET generate_document_type = COALESCE(enable_ai_metadata_creation, 0)")
    op.execute("UPDATE app_settings SET generate_tags = COALESCE(enable_ai_metadata_creation, 0)")
    
    with op.batch_alter_table('app_settings') as batch_op:
        batch_op.drop_column('enable_ai_metadata_creation')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_settings', sa.Column('enable_ai_metadata_creation', sa.Boolean(), nullable=True))
    op.execute("UPDATE app_settings SET enable_ai_metadata_creation = generate_tags")
    with op.batch_alter_table('app_settings') as batch_op:
        batch_op.drop_column('generate_correspondent')
        batch_op.drop_column('generate_document_type')
        batch_op.drop_column('generate_tags')
    # ### end Alembic commands ###
