"""Add metadata permissions settings

Revision ID: 50ebf5a59a86
Revises: 3c4d5e6f7a8b
Create Date: 2026-04-05 15:50:33.755256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50ebf5a59a86'
down_revision: Union[str, Sequence[str], None] = '3c4d5e6f7a8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metadata_owner_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('metadata_owner_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('metadata_view_users', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('metadata_view_groups', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('metadata_edit_users', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('metadata_edit_groups', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.drop_column('metadata_edit_groups')
        batch_op.drop_column('metadata_edit_users')
        batch_op.drop_column('metadata_view_groups')
        batch_op.drop_column('metadata_view_users')
        batch_op.drop_column('metadata_owner_id')
        batch_op.drop_column('metadata_owner_type')

    # ### end Alembic commands ###
