"""Add ollama timeout setting

Revision ID: 51bf10f9c974
Revises: 81706ec7e3d3
Create Date: 2026-03-29 11:49:28.082816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51bf10f9c974'
down_revision: Union[str, Sequence[str], None] = '81706ec7e3d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_settings', sa.Column('ollama_timeout', sa.Integer(), nullable=False, server_default=sa.text('300')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_settings', 'ollama_timeout')
    # ### end Alembic commands ###
