"""Remove metadata owner type

Revision ID: 53188b99c3e6
Revises: 50ebf5a59a86
Create Date: 2026-04-05 16:19:51.004625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53188b99c3e6'
down_revision: Union[str, Sequence[str], None] = '50ebf5a59a86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.drop_column('metadata_owner_type')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metadata_owner_type', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
