"""Add llamacpp settings

Revision ID: 65fb48795450
Revises: 13bde15ea57c
Create Date: 2026-04-04 19:27:03.067656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65fb48795450'
down_revision: Union[str, Sequence[str], None] = '13bde15ea57c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_backend', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('llamacpp_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('llamacpp_model', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('llamacpp_timeout', sa.Integer(), nullable=True))
        batch_op.alter_column('ollama_timeout',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('(300)'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.alter_column('ollama_timeout',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('(300)'))
        batch_op.drop_column('llamacpp_timeout')
        batch_op.drop_column('llamacpp_model')
        batch_op.drop_column('llamacpp_url')
        batch_op.drop_column('ai_backend')

    # ### end Alembic commands ###
