"""add metadata_use_system_defaults

Revision ID: 77c214df7ddd
Revises: 53188b99c3e6
Create Date: 2026-04-05 16:51:21.877523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77c214df7ddd'
down_revision: Union[str, Sequence[str], None] = '53188b99c3e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metadata_use_system_defaults', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.drop_column('metadata_use_system_defaults')

    # ### end Alembic commands ###
