"""Add update_creation_date setting

Revision ID: 81706ec7e3d3
Revises: e735d4aa3bff
Create Date: 2026-03-28 13:54:54.702928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81706ec7e3d3'
down_revision: Union[str, Sequence[str], None] = 'e735d4aa3bff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_settings', sa.Column('update_creation_date', sa.Boolean(), nullable=False, server_default=sa.text('0')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_settings', 'update_creation_date')
    # ### end Alembic commands ###
